FROM debian:bullseye-slim

SHELL ["/bin/bash", "-c"]

RUN set -euo pipefail && \
    apt-get update; \
    apt-get install --no-install-recommends -y \
        build-essential \
        ca-certificates \
        curl \
        jq \
        libmapnik-dev \
        python2.7 \
        ; \
    curl -fsSL https://deb.nodesource.com/setup_12.x | bash -; \
    apt-get install --no-install-recommends -y \
        nodejs \
        ; \
    rm -rf /var/lib/apt/lists/*; \
    :

WORKDIR /app
