#!/usr/bin/env bash
set -euo pipefail

ECR_FOLDER="${ECR_REGISTRY}/${FOLDER_NAME}"

docker tag "${IMAGE_NAME}:${TAG_NAME}" "${ECR_FOLDER}/${IMAGE_NAME}:${TAG_NAME}"
docker push "${ECR_FOLDER}/${IMAGE_NAME}:${TAG_NAME}"

docker tag "${IMAGE_NAME}:${TAG_NAME}" "${ECR_FOLDER}/${IMAGE_NAME}:${X_TAG_NAME}"
docker push "${ECR_FOLDER}/${IMAGE_NAME}:${X_TAG_NAME}"

docker tag "${IMAGE_NAME}:${TAG_NAME}" "${ECR_FOLDER}/${IMAGE_NAME}:${XY_TAG_NAME}"
docker push "${ECR_FOLDER}/${IMAGE_NAME}:${XY_TAG_NAME}"

docker tag "${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}" "${ECR_FOLDER}/${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}"
docker push "${ECR_FOLDER}/${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}"

docker tag "${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}" "${ECR_FOLDER}/${IMAGE_NAME}:${X_TAG_NAME}${OPENRESTY_SUFFIX}"
docker push "${ECR_FOLDER}/${IMAGE_NAME}:${X_TAG_NAME}${OPENRESTY_SUFFIX}"

docker tag "${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}" "${ECR_FOLDER}/${IMAGE_NAME}:${XY_TAG_NAME}${OPENRESTY_SUFFIX}"
docker push "${ECR_FOLDER}/${IMAGE_NAME}:${XY_TAG_NAME}${OPENRESTY_SUFFIX}"