#!/usr/bin/env bash
set -euo pipefail

docker tag "${IMAGE_NAME}:${TAG_NAME}" "${ECR_REGISTRY}/${IMAGE_NAME}:${TAG_NAME}"
docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${TAG_NAME}"

docker tag "${IMAGE_NAME}:${TAG_NAME}" "${ECR_REGISTRY}/${IMAGE_NAME}:${X_TAG_NAME}"
docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${X_TAG_NAME}"

docker tag "${IMAGE_NAME}:${TAG_NAME}" "${ECR_REGISTRY}/${IMAGE_NAME}:${XY_TAG_NAME}"
docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${XY_TAG_NAME}"

docker tag "${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}" "${ECR_REGISTRY}/${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}"
docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}"

docker tag "${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}" "${ECR_REGISTRY}/${IMAGE_NAME}:${X_TAG_NAME}${OPENRESTY_SUFFIX}"
docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${X_TAG_NAME}${OPENRESTY_SUFFIX}"

docker tag "${IMAGE_NAME}:${TAG_NAME}${OPENRESTY_SUFFIX}" "${ECR_REGISTRY}/${IMAGE_NAME}:${XY_TAG_NAME}${OPENRESTY_SUFFIX}"
docker push "${ECR_REGISTRY}/${IMAGE_NAME}:${XY_TAG_NAME}${OPENRESTY_SUFFIX}"