apiVersion: apps/v1
kind: Deployment
metadata:
  name: maps-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: maps-service
        image: 528757826541.dkr.ecr.ap-southeast-1.amazonaws.com/dsaidgovsg/sg-tileserver-gl:v1.1.0_tileserver-v3.1.1_mbtiles-0-18_20240612T202043Z_openresty
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        resources:
          requests:
            cpu: 500m
            memory: 4096Mi
          limits:
            cpu: '1'
            memory: 4096Mi
