---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2  # Will be patched in overlay
  selector:
    matchLabels:
      app: map-service
  template:
    metadata:
      labels:
        app: map-service
    spec:
      nodeSelector:
        node.kubernetes.io/worker-group: app
      containers:
      - name: map-service
        image: map-image:master  # Will be patched in overlay
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/openresty/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: template-nginx-conf

